\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle web notes

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top web notes

This manual is for program, version version.
@end ifnottex

@menu
* texinfo install::
* texinfo usage::
@c * Copying::  free time team
@end menu

@node texinfo install
@chapter texinfo install
@example
sudo apt-get install texi2html
texi2html test.texi
@end example

@node texinfo usage
@chapter texinfo usage

@b{add index}
@example
@@node Document
@@chapter Document
@@b@{Document@}
@@example
@@url@{./document/index.html, document@}
@@url@{./cs_dev/index.html, computer development@}
@@end example
@end example

@b{content}
@example
@@node test1
@@chapter test1
test content

@@node Free-time team test2
@@chapter Free-time team test2
test content
@end example

@bye
