\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle title

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top top

@end ifnottex

@menu
* Introduction::
* OpenCL setup on Intel Integrated GPU::
* CUDA free platform Introduction::
@c * Copying::  free time team
@end menu

@node Introduction
@chapter Introduction
随着人工智能技术、高性能计算应用越来越广泛，与之关系密切的异构计算平台也越来越普及。
目前比较流行的两大计算平台分别是 OpenCL 和 CUDA。
如果想学习这方面的技术，购买 GPU 是一条常见的路径。本文会提供一些相对低成本一点的方法。
目前几乎稍微主流一点的 intel 处理器，都会有集成显卡，因此我们会介绍OpenCL在intel集成显卡上环境搭建的方法。
Nvidia 的显卡一般都很贵，但是很多平台提供了免费平台可以使用 Nvidia 的显卡，我们会以百度的飞桨平台为例做介绍。

@node OpenCL setup on Intel Integrated GPU
@chapter OpenCL setup on Intel Integrated GPU

@node CUDA free platform Introduction
@chapter CUDA free platform Introduction

@bye
